repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
  - repo: https://github.com/ambv/black
    rev: "23.11.0"
    hooks:
      - id: black
  - repo: https://github.com/lovesegfault/beautysh
    rev: "v6.2.1"
    hooks:
      - id: beautysh
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.33.0"
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox
        language: system
        types: [python]
        pass_filenames: false

